version: '3.8'
services:
  pokedex-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - /BACKEND:/BACKEND
      - /node_modules

    #command: sh -c "npm install && nodemon index.js"
